AWSTemplateFormatVersion: 2010-09-09
Description: >-
  invokeA

Transform:
- AWS::Serverless-2016-10-31

Resources:
  helloFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/hello-from-lambda.helloFromLambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 900
      Description: A Lambda function that returns a static string.
      Policies:
        - AWSLambdaBasicExecutionRole
